version: "1.0"
services:
  ftpd-server:
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - './ftp/data:/home/username/'
      - './ftp/pass:/etc/pure-ftpd/passwd'
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: "liviu"
      FTP_USER_PASS: "pass"
      FTP_USER_HOME: "/home/username"
    restart: always